---
- name: Uninstall Nginx from Ubuntu 22.04
  hosts: all
  become: yes

  tasks:
    - name: Stop Nginx service
      service:
        name: nginx
        state: stopped
      ignore_errors: yes

    - name: Uninstall Nginx package
      apt:
        name: nginx
        state: absent